### ISSUE TITLE
Sizes of your MakerBeam Panels 

### ISSUE THREAD

**Issue by Vernon3D** [naitzabez/VSW_Mods#1]
Hello there,
 
I missing the sizes of the panels For the MakerBeamxl enclosure you desgined

**Comment by sebbevallin** [comment]
This project was abandoned (and the printer is sold), if i recall correctly the panels where overlapping the extrusions by 4mm of their 15mm width, so if i have an open space from (0,0), (0,10), (10,0), (10,10) between the extrusions, the panels would be (-4,-4) (-4,14) (14,-4) (14,14) if that makes sense
